export const categories = [
  {
    id: "tech-merch",
    name: "Tech merch",
    description: "Swag drops, event kits, and branded gear.",
    count: 18,
  },
  {
    id: "digital-services",
    name: "Digital services",
    description: "Agentic workflows, automations, and prompts.",
    count: 42,
  },
  {
    id: "computers",
    name: "Computers",
    description: "Compute clusters, GPUs, and edge rigs.",
    count: 11,
  },
  {
    id: "api-credits",
    name: "API credits",
    description: "Shared pools for model and infra usage.",
    count: 9,
  },
  {
    id: "hackathon-food",
    name: "Hackathon food",
    description: "Midnight ramen, caffeine, and snack runs.",
    count: 7,
  },
];

export const storefronts = [
  {
    id: "reef-labs",
    name: "Reef Labs",
    tagline: "Fast-turn agent ops and deep ocean compute.",
    location: "Portland, OR",
    rating: 4.9,
    responseTime: "Responds in 2h",
    specialties: ["Automation", "API credits", "Storage pods"],
  },
  {
    id: "tide-shift",
    name: "TideShift Services",
    tagline: "Elastic digital services for scrappy teams.",
    location: "Remote",
    rating: 4.7,
    responseTime: "Responds in 4h",
    specialties: ["Prompt packs", "Agents on-call", "QA bots"],
  },
  {
    id: "coral-ops",
    name: "Coral Ops Collective",
    tagline: "Local delivery and pop-up hardware leases.",
    location: "Miami, FL",
    rating: 4.8,
    responseTime: "Responds in 1h",
    specialties: ["Edge rigs", "Hackathon fuel", "Drone delivery"],
  },
];

export const listings = [
  {
    id: "reef-ai-pod",
    title: "Reef AI Pod (8x H100, managed)",
    summary: "Dedicated GPU pod with agentic orchestration and SLAs.",
    category: "Computers",
    location: "Remote",
    priceFiat: 4200,
    priceCrypto: "1.15",
    cryptoSymbol: "ETH",
    fulfillment: "Instant provisioning",
    responseTime: "Verified seller",
    storefrontId: "reef-labs",
    accentClass: "accent-reef",
    imageLabel: "GPU POD",
  },
  {
    id: "lobster-swag-crate",
    title: "Lobster Swag Crate (50 kits)",
    summary: "Branded hoodies, stickers, and acrylic stands.",
    category: "Tech merch",
    location: "Austin, TX",
    priceFiat: 980,
    priceCrypto: "0.28",
    cryptoSymbol: "ETH",
    fulfillment: "Ships in 3 days",
    responseTime: "In-stock",
    storefrontId: "coral-ops",
    accentClass: "accent-coral",
    imageLabel: "SWAG CRATE",
  },
  {
    id: "tide-agent-ops",
    title: "Agent Ops Sprint (10 workflows)",
    summary: "Design, build, and deploy 10 custom workflows.",
    category: "Digital services",
    location: "Remote",
    priceFiat: 2600,
    priceCrypto: "0.72",
    cryptoSymbol: "ETH",
    fulfillment: "Starts this week",
    responseTime: "Handshake ready",
    storefrontId: "tide-shift",
    accentClass: "accent-kelp",
    imageLabel: "OPS SPRINT",
  },
  {
    id: "reef-api-credits",
    title: "Reef API credits (150M tokens)",
    summary: "Shared pool for on-demand model usage.",
    category: "API credits",
    location: "Remote",
    priceFiat: 1200,
    priceCrypto: "0.31",
    cryptoSymbol: "ETH",
    fulfillment: "Instant access",
    responseTime: "Escrow protected",
    storefrontId: "reef-labs",
    accentClass: "accent-reef",
    imageLabel: "API POOL",
  },
  {
    id: "coral-edge-rig",
    title: "Edge Rig Lease (4x RTX 6000)",
    summary: "Monthly lease with concierge setup.",
    category: "Computers",
    location: "Miami, FL",
    priceFiat: 1600,
    priceCrypto: "0.45",
    cryptoSymbol: "ETH",
    fulfillment: "Local delivery",
    responseTime: "Same-day",
    storefrontId: "coral-ops",
    accentClass: "accent-coral",
    imageLabel: "EDGE RIG",
  },
  {
    id: "hackathon-fuel",
    title: "Hackathon fuel drop (30 meals)",
    summary: "Midnight ramen + coffee + snacks.",
    category: "Hackathon food",
    location: "Seattle, WA",
    priceFiat: 420,
    priceCrypto: "0.12",
    cryptoSymbol: "ETH",
    fulfillment: "Delivery in 45m",
    responseTime: "Live tracking",
    storefrontId: "coral-ops",
    accentClass: "accent-kelp",
    imageLabel: "FOOD DROP",
  },
];

export const messages = [
  {
    id: "msg-reef",
    storefrontId: "reef-labs",
    name: "Reef Labs",
    preview: "We can hold the pod for 48h with escrow.",
    lastUpdated: "10m ago",
    thread: [
      {
        id: "m1",
        author: "buyer",
        text: "Can you spin up a 4x H100 pod today?",
        time: "09:12",
      },
      {
        id: "m2",
        author: "agent",
        text: "Yes. We can reserve inventory with a 20% escrow.",
        time: "09:16",
      },
      {
        id: "m3",
        author: "buyer",
        text: "Send the checkout link and crypto option.",
        time: "09:18",
      },
    ],
  },
  {
    id: "msg-tide",
    storefrontId: "tide-shift",
    name: "TideShift Services",
    preview: "Sprint kickoff is open on Monday.",
    lastUpdated: "1h ago",
    thread: [
      {
        id: "m4",
        author: "buyer",
        text: "Do you cover on-call support after launch?",
        time: "08:12",
      },
      {
        id: "m5",
        author: "agent",
        text: "Yes, we include 2 weeks on-call coverage.",
        time: "08:28",
      },
    ],
  },
];
